### ISSUE TITLE
Commands Problem

### ISSUE THREAD

**Issue by spitafifire** [daltonyxdonovan/WobblyLife_ConsoleCommands#2]
Whenever someone new joins the lobby, like an alt. The commands get transferred to them, is there a way this can be fixed, or is there some sort of menu to change who gets affected?

**Comment by daltonyxdonovan** [comment]
there isn't a way to change it, no. Honestly, I'm surprised the mod still works after all this time! I made that when Wobbly Life had just released and maintained it for a few months, but then quit modding games and shut down the community to be honest. 

Because it was an early access game when I was modding it, the code kept changing every update and would break multiple things. I played the cat and mouse game for a while and then just didn't want to anymore. Sorry that it isn't working as expected dude
